#!/usr/bin/env python3
"""
Pulls the latest issue of Peter's Beehiiv newsletter into newsletter.html.

Same idea as build-podcast.py: fetch a public RSS feed at build time and write
static HTML into the page, so visitors never wait on a third-party request and
Google sees real content.

Why build-time and not a browser fetch: the Beehiiv feed sends no CORS headers,
so JavaScript on peterlohmann.com is not allowed to read it. Beehiiv also has no
official "embed this post" widget, and iframing a post drags in their whole page
chrome (logo, Login/Subscribe buttons, nav). Pulling the feed lets us render the
issue in Peter's own fonts and styling instead.

The feed ships email-formatted HTML: a <style> block that forces Helvetica with
!important, plus inline font/color/width rules on nearly every tag. sanitize()
strips exactly those so the site's typography wins, while leaving the writing,
links, images, and structure intact.

Run:  python3 build-newsletter.py
"""

import html as ihtml
import os
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
PAGE = os.path.join(HERE, "newsletter.html")
FEED = "https://rss.beehiiv.com/feeds/iue8pEsTvJ.xml"
# Beehiiv sits behind Cloudflare, which 403s a default urllib user-agent.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/128.0 Safari/537.36")

CONTENT = "{http://purl.org/rss/1.0/modules/content/}encoded"
START, END = "<!-- NEWSLETTER-LATEST:START -->", "<!-- NEWSLETTER-LATEST:END -->"


def fetch_feed():
    req = urllib.request.Request(FEED, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=45) as r:
        return ET.fromstring(r.read())


def sanitize(raw):
    """Turn Beehiiv's email HTML into markup that inherits the site's design."""
    h = raw

    # 1. Drop the email <style> block (Helvetica !important, table chrome).
    h = re.sub(r"<style\b[^>]*>.*?</style>", "", h, flags=re.S | re.I)
    # 2. No scripts should ever come through, but never trust the feed.
    h = re.sub(r"<script\b[^>]*>.*?</script>", "", h, flags=re.S | re.I)

    # 3. Strip the inline declarations that fight the site's typography and layout.
    #    Everything else in the style attribute (text-align, font-weight, etc.) stays.
    kill = re.compile(
        r"\s*(?:font-family|font-size|line-height|color|background-color|background"
        r"|width|max-width|min-width|height|max-height|min-height)\s*:[^;\"']*;?",
        re.I)

    def clean_style(m):
        val = kill.sub("", m.group(1)).replace("!important", "").strip(" ;")
        return f' style="{val}"' if val else ""

    h = re.sub(r'\s*style="([^"]*)"', clean_style, h)
    h = re.sub(r"\s*style='([^']*)'", lambda m: clean_style(m), h)

    # 4. Hard width/height attributes on images and tables break the fluid layout.
    h = re.sub(r'\s(?:width|height|align|bgcolor)="[^"]*"', "", h, flags=re.I)

    # 5. Images: lazy-load, and let CSS size them.
    h = re.sub(r"<img\b", '<img loading="lazy" decoding="async"', h, flags=re.I)

    # 6. Every link leaves the site, so open in a new tab safely.
    h = re.sub(r"<a\s+(?![^>]*\btarget=)", '<a target="_blank" rel="noopener" ', h, flags=re.I)

    # 7. Beehiiv wraps everything in .beehiiv / .beehiiv__body; our own wrapper replaces it.
    h = re.sub(r'</?div class=[\'"]beehiiv(?:__body)?[\'"]>', "", h)

    # 8. Drop Beehiiv's trailing email footer ("Powered by beehiiv" promo badge).
    #    It is always the last element, so cut from there to the end.
    h = re.sub(r"<div class=['\"]beehiiv__footer['\"].*$", "", h, flags=re.S)

    return h.strip()


def fmt_date(pub):
    for f in ("%a, %d %b %Y %H:%M:%S %z", "%a, %d %b %Y %H:%M:%S %Z"):
        try:
            return datetime.strptime(pub, f).astimezone(timezone.utc).strftime("%b %-d, %Y")
        except ValueError:
            pass
    return ""


def main():
    root = fetch_feed()
    items = root.find("channel").findall("item")
    if not items:
        print("ERROR: feed returned no items; newsletter.html not changed.")
        sys.exit(1)

    it = items[0]
    title = ihtml.escape((it.findtext("title") or "Latest issue").strip())
    link = (it.findtext("link") or "").strip()
    date = fmt_date((it.findtext("pubDate") or "").strip())
    body = sanitize(it.findtext(CONTENT) or "")

    if len(body) < 500:
        print(f"ERROR: latest issue body was only {len(body)} chars; newsletter.html not changed.")
        sys.exit(1)

    block = f"""{START}
      <!-- Generated by build-newsletter.py from the Beehiiv RSS feed. Do not hand-edit. -->
      <div class="nl-latest-head">
        <span class="tag tag-blue">Latest issue</span>
        <h3>{title}</h3>
        <p class="nl-latest-date">{date}</p>
      </div>
      <div class="nl-preview">
        <div class="nl-paper" id="nlPaper">
          <div class="nl-doc">
{body}
          </div>
        </div>
        <div class="nl-fade" aria-hidden="true"></div>
      </div>
      <div class="nl-actions">
        <button type="button" class="nl-zoom" id="nlZoom" aria-label="Read the full issue">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
               stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <circle cx="11" cy="11" r="7"></circle><path d="m20 20-3.5-3.5"></path>
            <path d="M11 8v6M8 11h6"></path>
          </svg>
          <span>Read full issue</span>
        </button>
        <a class="nl-open" href="{link}" target="_blank" rel="noopener">Open on beehiiv &rarr;</a>
      </div>
      {END}"""

    page = open(PAGE, encoding="utf-8").read()
    if START not in page or END not in page:
        print("ERROR: markers not found in newsletter.html; nothing changed.")
        sys.exit(1)

    new = page[:page.index(START)] + block + page[page.index(END) + len(END):]
    open(PAGE, "w", encoding="utf-8").write(new)

    print(f"Latest issue: {ihtml.unescape(title)} ({date})")
    print(f"  {link}")
    print(f"  {len(body):,} chars of sanitized HTML written into newsletter.html")


if __name__ == "__main__":
    main()
